services:
  # chainindex node
  chaindex:
    image: local/chainindex:latest
    command: ["-blockchain-type=mainnet"]
    ports:
    - "16061:16061"
  # indexed-chain nodes
  ethereum:
    image: local/geth:latest
    ports:
    - "30303:30303"
    expose:
    - "8545"
    - "8546"
    command: "--syncmode light --mainnet --http --http.api eth,net --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=*"
  bitcoin:
    image: local/bitcoin-core:latest
    ports:
    - "8333:8333"
    expose:
    - "8332"
    command: "-chain=main -server -rpcbind=:8332 -rpcallowip=0.0.0.0/0"

